### ISSUE TITLE
Running Leakcanary will be crashed by app use SmartSwipe

### ISSUE THREAD

**Issue by vds2000** [luckybilly/SmartSwipe#8]
Dear billy,
I use Leakcanary to check app memory leak. But if app use SmartSwipe, when exit app and open Leakcanary , it will be crashed.
The logcat info below:
com.billy.android.swipe.demo:leakcanary E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.billy.android.swipe.demo:leakcanary, PID: 18929
    java.lang.ClassCastException: com.billy.android.swipe.SmartSwipeWrapper$LayoutParams cannot be cast to com.android.internal.widget.ActionBarOverlayLayout$LayoutParams
        at com.android.internal.widget.ActionBarOverlayLayout.applyInsets(ActionBarOverlayLayout.java:290)
        at com.android.internal.widget.ActionBarOverlayLayout.onMeasure(ActionBarOverlayLayout.java:436)
        at android.view.View.measure(View.java:19734)
        at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6120)
        at android.widget.FrameLayout.onMeasure(FrameLayout.java:185)
        at com.android.internal.policy.DecorView.onMeasure(DecorView.java:687)
        at android.view.View.measure(View.java:19734)
        at android.view.ViewRootImpl.performMeasure(ViewRootImpl.java:2271)
        at android.view.ViewRootImpl.measureHierarchy(ViewRootImpl.java:1358)
        at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1607)
        at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1246)
        at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6301)
        at android.view.Choreographer$CallbackRecord.run(Choreographer.java:871)
        at android.view.Choreographer.doCallbacks(Choreographer.java:683)
        at android.view.Choreographer.doFrame(Choreographer.java:619)
        at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:857)
        at android.os.Handler.handleCallback(Handler.java:751)
        at android.os.Handler.dispatchMessage(Handler.java:95)
        at android.os.Looper.loop(Looper.java:154)
        at android.app.ActivityThread.main(ActivityThread.java:6077)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:866)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:756)

Would you like to help to fix it?
Thanks

**Comment by luckybilly** [comment]
@vds2000 Thank you for your feedback, it is a bug and fixed by version 1.0.1 
Thanks again!

**Comment by vds2000** [comment]
> @vds2000 Thank you for your feedback, it is a bug and fixed by version 1.0.1
> Thanks again!

Tranks for your help~!
